Migrating project to use groups in allowlist
ministryofjustice/hmpps-temporary-accommodation-ui pull request #732
Opened 2023-11-09 10:06 UTC by andrewrlee

This PR migrates the project to use groups of IPs in their allowlist.

By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.

1 allowlist(s) have been detected that can be migrated.

## Allowlist: helm_deploy/hmpps-temporary-accommodation-ui/values.yaml

### New Groups

The effect of applying this PR is as follows:

- The following groups will be applied: `internal,prisons`
- The size of the allowlist defined in this file will change: `15 => 0 (15 removed)`

### Added IPs

The new Group membership will result in the following IPs being added to your allowlist by applying this PR:

- moj-official-tgw-prod
  

- moj-official-tgw-preprod
  

- moj-official-ark-c-vodafone
  

- moj-official-ark-f-vodafone
  

- mojo-azure-landing-zone-public-egress-1
  

- mojo-azure-landing-zone-public-egress-2
  

- mojo-azure-landing-zone-public-egress-3
  

- mojo-azure-landing-zone-public-egress-4
  

### Removed IPs

The following IPs have been identified as unnecessary and will be removed by applying this PR:

- health-kick

2023-11-21 13:07 UTC, tahb requested changes
Hey Andrew, thanks for this, we definitely need to proactively allow the right IP ranges 👍 

Some questions around version changes.

And in general, has this changeover been tested by any other service yet? If not, I think we should consider trying this on preprod first and testing it out.

2023-11-21 13:07 UTC, tahb commented on helm_deploy/hmpps-temporary-accommodation-ui/Chart.yaml
> +    version: "2.8"
What's the rational for removing the patch and going backwards? Is this not a downgrade?

2023-11-21 13:07 UTC, tahb commented on .circleci/config.yml
> +  hmpps: ministryofjustice/hmpps@7
Again, what's the rationale with this one? What breaks without this change? Is setting only the major here not the equivalent of a downgrade? [It looks like the latest version number of 7 is 7.5.1](https://circleci.com/developer/orbs/orb/ministryofjustice/hmpps).

2024-06-10 12:26 UTC, andrewrlee commented on .circleci/config.yml
> +  hmpps: ministryofjustice/hmpps@7
btw- this wasn't a downgrade, we recommend floating on the major version of the orb and helm chart

2024-06-10 13:45 UTC, froddd commented
Superseded by #983

2024-06-10 13:45 UTC, closed without merging